### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by xuwenxin2** [AlvaroCavalcante/auto_annotate#12]
(tensorflow) zhu@zhu-Nitro-AN515-51:~/auto_annotate$ python3 scripts/detection_images.py
2021-04-06 18:16:53.498679: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/melodic/lib
2021-04-06 18:16:53.498699: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

WARNING:tensorflow:From /home/zhu/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "scripts/detection_images.py", line 45, in <module>
    od_graph_def.ParseFromString(serialized_graph)
google.protobuf.message.DecodeError: Error parsing message

I'm new to this. I try to find answer from stackoverflow but nothing can help.
I'm using Tensorflow 2.4

**Comment by xuwenxin2** [comment]
somehow i found out that the problem is my "frozen_inference_graph.pb" file problem.
cause i try with frozen_inference_graph from tensorflow and this problem is solved.

But I got other problem.

Traceback (most recent call last):
  File "scripts/detection_images.py", line 141, in <module>
    vis_util.visualize_boxes_and_labels_on_image_array(
TypeError: visualize_boxes_and_labels_on_image_array() got an unexpected keyword argument 'file_name'

I have visulize on "visualization_utils.py" and I didn't found anything that might be wrong.
Please help.

**Comment by AlvaroCavalcante** [comment]
Hello @xuwenxin2, I'll be happy to help you! 
Well, this error just means that you are calling the method with a parameter that doesn't exist. If we analyze, in the **detection_images.py** we call the method ```visualize_boxes_and_labels_on_image_array``` with a parameter called "file_name". This parameter doesn't exist in the original TF implementation, that's why you need to add it.

In my tutorial on [Medium](https://medium.com/analytics-vidhya/auto-annotate-images-for-tensorflow-object-detection-19b59f31c4d9) I explain that you need to replace the content of your **"visualization_utils.py"** by the **"visualization_utils.py"** that is inside the folder "scripts" in this repository. Also, you will need to copy and paste the file "generate_xml.py" in the same folder that your **"visualization_utils.py"** file is.

**Comment by AlvaroCavalcante** [comment]
I'll close this issue due to the inactivity, if you need help, open it again!
