### ISSUE TITLE
visualize_boxes_and_labels_on_image_array() got an unexpected keyword argument 'file_name'

### ISSUE THREAD

**Issue by Laudarisd** [AlvaroCavalcante/auto_annotate#14]
Now I am stuck in this issue?

Could you please help me?
I am using tf 2.0 in docker.
is it because of tf version? 

Thank you.

**Comment by AlvaroCavalcante** [comment]
No, your version is ok! This error is happening because you probably didn't follow the step of replacing your visualization_utils.py file in your models/research folder by mine. You can find complete instructions on how to run this project in this article: https://medium.com/analytics-vidhya/auto-annotate-images-for-tensorflow-object-detection-19b59f31c4d9, but I'll try to explain to you here.

- So, first of all, as this is an object detection problem, you'll need to clone the TensorFlow official repository: https://github.com/tensorflow/models.
- After that, inside the folder research/object detection/utils you'll find a file named visualization_utils.py. Replace the content of this file with the content of the visualization_utils.py that is in this repository.
- Copy the generate_xml.py file, that is in this repository, and past it in the same folder of the visualization_utils.py. (research/object detection/utils)

It seems a little hard, but I think that if you follow the steps described here and explained in the article you'll get this without problems!

**Comment by Laudarisd** [comment]
Thanks for your reply. I will follow these steps. Let see how it goes.

Thank you

**Comment by Laudarisd** [comment]
I followed the instructions that you provided. I replace visualization_utils file with your file. 
Still I am getting same error.
I also tried to move models folder inside of your repository folder but still same issue. 
Couldn't solve.

**Comment by AlvaroCavalcante** [comment]
@Laudarisd, well, it's really strange that this error is still happening... somehow you're not using my version of visualization_utils.py. I know that because the error that you're showing is very simple! If you analyze this line of code you'll see that I'm passing the "file_name" variable defined before as an argument to the "visualize_boxes_and_labels_on_image_array" method:

https://github.com/AlvaroCavalcante/auto_annotate/blob/22d14395e3916d28d114a0aac8631623ccdede51/scripts/detection_images.py#L137-L146

It turns out that this parameter (file_name) doesn't exist in the "visualize_boxes_and_labels_on_image_array" of the original TensorFlow repository, so you get this error.

Try to debug your code to find where is the path of the visualization_utils.py file that your code is calling. Once you find this file, replace its content with mine.

Another possible solution is to open a terminal, enter in the models/research folder (that you cloned from the TensorFlow repo) and set it as your python path with this line:
```export PYTHONPATH=$(pwd)```

After that, using the same terminal that you pasted it, go to the scripts folder of this repository and try to execute the code again. 

This will force your code to be run using the models/research content, and if you replace the visualization_utils.py that is in there, you'll not get this error anymore.

**Comment by AlvaroCavalcante** [comment]
I'll close this due to inactivity!

**Comment by Laudarisd** [comment]
Sorry, couldn't reply on time. I couldn't solve the problem. I just tried to save annotation files from yolo framework. That worked for me. Thank you for your time.

**Comment by nkulkarni3297** [comment]
@AlvaroCavalcante, I tried with the same part of the code section as mentioned in our above comment to resolve but still I am getting the same error. Also, while trying the cmd command suggested by you `export PYTHONPATH=$(pwd)` it shows me error. It would be great if you could help me with the issue.

![image](https://user-images.githubusercontent.com/78587643/188111419-8a6950e3-840a-479f-a41b-f992e11fd11c.png)

**Comment by nkulkarni3297** [comment]
Hi, I was able to get the alternative for `export PYTHONPATH=$(pwd)` in windows. If anyone is using windows then they need to use `set PYTHONPATH=$(pwd)` instead of `export`. 

But solution for the file_name error is still the same for me after setting the pythonpath.

**Comment by AlvaroCavalcante** [comment]
Hello @nkulkarni3297, sorry for the late response and thank you for finding an alternative solution to set the python path on windows, as I'm not a windows user, this would be hard for me!

About the error in the "file_name" argument, it turns out that this argument it's not native to TensorFlow, I've added it into a modified version of the "visualization_utils.py" script. Because of that, you need to use my modified version instead of the TensorFlow version. At the beginning of the "detection_img_tf2.py" script, you can see this line:

```
from object_detection.utils import visualization_utils as viz_utils
```
This is saying that we are importing the **visualization_utils** script from the folder **object_detection/utils***. This folder is inside the "models/research" folder from the TensorFlow Garden, which you have cloned (as I can see on your print screen). 

That said, a possible solution for this error is to open the folder "models/research/object_detection/utils" and find the file "visualization_utils.py" inside. After this, you can delete this file and replace it with my [visualization_utils.py](https://github.com/AlvaroCavalcante/auto_annotate/blob/master/scripts/visualization_utils.py).

After this, the error may be resolved! 

Another possible solution could be to change the import to use the correct script, maybe something like this:
```
import visualization_utils as viz_utils
```
If you still find any problems, feel free to ask and give me more details, I'm happy to help you!!

Besides that, I'll release a new version of this library in the future that will be easier to use.

**Comment by nkulkarni3297** [comment]
Hello @AlvaroCavalcante, Thank you so much for your precious suggestion. So here it what I did from your suggestion which would be helpful to all I suppose:

Firstly this solution has worked with the current available Tensorflow version 2.9.0

So, as you suggested in all solutions to replace "visualizations_utils.py" file with yours in "models/research/object_detection/utils* folder. I was earlier trying with the same solution but I was still getting the same error of "file_name". 

Your second suggestion was to do changes in  "detection_img_tf2.py" script. So in this file

line 9 says 
`from object_detection.utils import visualization_utils as viz_utils` 

which I replaced with your suggestion to
`import visualization_utils as viz_utils`

After doing the change and running the code it gave me another error from the file of visualizations_utils.py stating
**ImportError: cannot import name 'generate_xml' from 'object_detection.utils'**
In this file line 26 says
`from object_detection.utils import generate_xml`

which I changed to this
`import generate_xml`

And on running this script again after these changes, it successfully executed and also generated the xml files on the provided location in "generate_xml.py" file in line 36.

Also this solution worked keeping the `file_name = file_name` in "detection_img_tf2.py" file at line 36 which was actual point of having the error.

Thank you so much once again @AlvaroCavalcante for your help and also @Laudarisd for opening this issue.

**Comment by AlvaroCavalcante** [comment]
That's great @nkulkarni3297!!

If you have another trouble, don't hesitate to open a new issue.

Besides that, If this project was useful for you, please, follow it to see the future updates, my intention is to create a pip library that will be easier to use!

**Comment by nkulkarni3297** [comment]
Hello AlvaroCavalcante,

Thank you so much for your reply. As currently I am in India and having the
time difference from yours, I'll go tomorrow in the office and I'll
definitely try the solution you have suggested and will let you know for
updates.

Thanks and Regards
Ninad Kulkarni
