### ISSUE TITLE
ImportError: cannot import name 'string_int_label_map_pb2' from 'object_detection.protos' (/home/sumukha/Desktop/auto_annotate-master/scripts/object_detection/protos/__init__.py)

### ISSUE THREAD

**Issue by sumukhaadiga02** [AlvaroCavalcante/auto_annotate#15]
The above error occurs while running detection_images.py. Please help me resolving the issue

**Comment by AlvaroCavalcante** [comment]
Hello @sumukhaadiga02, I've never seen this error before in my project, what TensorFlow version are you using? Did you install all the requirements for running an object detection API? Try to run some example projects inside models/research/object-detection in the TensorFlow repo and see if it works! This seems like a problem in your environment.

**Comment by sumukhaadiga02** [comment]
Thanks. I have another doubt. What is the meaning of that **frozen_inference_graph.pb** file which should we added to /graphs folder.

**Comment by AlvaroCavalcante** [comment]
frozen_inference_graph.pb is just your trained model! They call the file frozen because the weights of the network can't be trained anymore, it's a final version of your model. In version 1.x of TensorFlow, it was very common to get frozen_inference_graphs as a result of training the model, that's why I'm using this idea here. Today, it's usual to have some checkpoint files, that can be retrained if you want. So, you can adapt the inference code to run with your checkpoints or you can also easily convert your checkpoints to one frozen_inference_graph.pb file that will be pasted in the folder and used in this project!

**Comment by AlvaroCavalcante** [comment]
I'll close this due to inactivity!

**Comment by sumukhaadiga02** [comment]
Sorry for not replying. Thank you
