### ISSUE TITLE
XML files are not generated when I run detection_images.py script 

### ISSUE THREAD

**Issue by DeepakShanthaiah** [AlvaroCavalcante/auto_annotate#4]
On running detection_images.py script ,xml files are not been created but I can see the annotated images in result folder.
Tensorflow version I am using is 1.14.
I didn't get any error nor any warning.

Please let me know how to generate the XML files now as it is whole point of doing auto annotation @AlvaroCavalcante

**Comment by AlvaroCavalcante** [comment]
Hello @DeepakShanthaiah, will be a pleasure the help you! What's happening to you is strange, since just running the detection_images.py is enough to generate the XML files. It turns out that if your model doesn't predict any object, the XML creation is skipped, as we can check here: https://github.com/AlvaroCavalcante/auto_annotate/blob/d08e728047ba3374bd414f7d2427746811687895/scripts/visualization_utils.py#L896

Verify if your model is predicting any object (as you said that you see the annotated images) and add a print ou a breakpoint in the line in the link, to check if the information is passed successfully to the generate_xml.py! 

Let me know your results :)

**Comment by DeepakShanthaiah** [comment]
Hello @AlvaroCavalcante , I have debugged that error and I am able to get the xml files but now one more issue I am facing is , In the image that i have given to test I have around 5 classes in one image and I am getting the bounding box for all classes but labels are not different when I open the XML files . For example : If My classes are A ,B,C,D,E I am getting 5 bounding box but all the labels are either A or B or C or D or E ...I am just getting one class name for all bounding boxes.

So how to tackle this thing now to get corresponding label name for its bounding boxes accordingly ?

**Comment by AlvaroCavalcante** [comment]
@DeepakShanthaiah in the GenerateXml you can check that the class you get in XML file is the same as your model predicted passed as a parameter. But "class_name" is a string variable as its value is set here:
https://github.com/AlvaroCavalcante/auto_annotate/blob/d08e728047ba3374bd414f7d2427746811687895/scripts/visualization_utils.py#L822

It turns out that this variable may be a list, here you must append your classes. 

After transforming this variable into a list, you must replace the following line with the correct syntax to get to class from the list. 
https://github.com/AlvaroCavalcante/auto_annotate/blob/d08e728047ba3374bd414f7d2427746811687895/scripts/generate_xml.py#L33

An alternative is to change the dictionary that goes inside the "array_position" list with a property "class" and getting the right class when in the for loop.

https://github.com/AlvaroCavalcante/auto_annotate/blob/d08e728047ba3374bd414f7d2427746811687895/scripts/visualization_utils.py#L850

Let me know if you of these suggestions works, It would be great if you did a pull request if this changes. Thank you!

**Comment by DeepakShanthaiah** [comment]
Hey @AlvaroCavalcante  Thanks for your suggestions. I followed the steps you suggested to convert the string variable into list in Visualization_utils.py  and modifies the code in generate_xml.py file  and I got the result as expected.

Thanks for your support.

**Comment by AlvaroCavalcante** [comment]
@DeepakShanthaiah Thank you for your contribution to this project, if you have some time, create a Pull Request with your changes so other people can solve this possible issue! I'll close this issue, any other doubt I'm here to help!
