### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Ogafais** [AlvaroCavalcante/auto_annotate#7]
list index out of range error when run the code...please help

**Comment by AlvaroCavalcante** [comment]
Sure, I'm glad to help you. Can you tell me your TF version, please? This project was done in TF 1.14, so probably you will need to do some adaptations when using TF 2.0.

Furthermore, could you please tell me where did the error raises? Thank you.

**Comment by Ogafais** [comment]
Hi, i already manage to solve that problem but now i having problem where XML in not produce even i can see the images in result folder with correctly labelled

**Comment by AlvaroCavalcante** [comment]
Ok @Ogafais, your problem seems to be similar to this issue: https://github.com/AlvaroCavalcante/auto_annotate/issues/4. Please, read this issue too: https://github.com/AlvaroCavalcante/auto_annotate/issues/5.

In these issues, we had a good discussion about the possibilities of getting this kind of error. If you still have this problem after that, please, detail for me how are you running the script and exactly where are you getting the error, and I'll help you! Thanks a lot :)

**Comment by AlvaroCavalcante** [comment]
I'll close this issue due to inactivity, if you have this problem again, please, reopen this issue!
