### ISSUE TITLE
xml for multiple class names

### ISSUE THREAD

**Issue by andhana** [AlvaroCavalcante/auto_annotate#8]
Hello @AlvaroCavalcante , this script is running well. 
I have multiple class names and it appears in the detected image, but I only get one class name for all bounding box in the xml file.
Could you help me please? 
Thank you

**Comment by AlvaroCavalcante** [comment]
@andhana I'll be happy to help you! Your problem seems to be similar to this: https://github.com/AlvaroCavalcante/auto_annotate/issues/4#issuecomment-735710994. If you debug the visualization_utils.py file you will rapidly find the source of your problem, look at this snippet: 

```
if new_xml != False:
      xml = generate_xml.GenerateXml(array_position, im_width, im_height, class_name, file_name)
      xml.gerenate_basic_structure()
```
Here is where we call the GenerateXml class, one of the parameters is the class_name of the detected object. Please, verify if the name is being correctly passed!

**Comment by andhana** [comment]
Thank you for your response. 
I already run the script exactly same with your code from github (I only change the directory path with mine), but the result is still get one class name. Any suggestion?

**Comment by AlvaroCavalcante** [comment]
Maybe there's a bug in the system! To discover that, I'll need you to find what part of the code the things stop to work as it should. My suggestion is that you put a ```print(class_name)```  right below this IF: https://github.com/AlvaroCavalcante/auto_annotate/blob/600406a470f400795a1010656aa222cf48dabcae/scripts/visualization_utils.py#L897.

After that, tell me what was the result of the print, if your classes are correctly printed or if the bug begins before this point! Thank you.

**Comment by andhana** [comment]
After I print, the result is just "person" class name. 
In the image bounding box is  "person" and "N/A". It should be "person" and "kite".

**Comment by AlvaroCavalcante** [comment]
@andhana It means that your problem is not in the generate_xml.py file, which is the file responsible to create the XML file with the annotations. Maybe there's something wrong with your visualization_utils.py file. What's your TF version? Could you show me your result image? If your model is openly available, I could try to debug it for you! Thanks!

**Comment by andhana** [comment]
The "N/A" bounding box was fixed, I forgot to change max_num_class according .pbtxt file.
But the xml file still write one class.

- TF version = tensorflow-gpu==1.13.0
- model = faster_rcnn_inception_v2_coco_2018_01_28 and ssd_mobilenet_v1_coco_2017_11_17
- Labels = mscoco_label_map.pbtxt

Thank you @AlvaroCavalcante

**Comment by AlvaroCavalcante** [comment]
@andhana the version that I used in my tests was the TF 1.14, but I'm not sure if this is a problem. Now that you fixed the "N/A" class, something different is being printed in the "class_name" or your unique result is still "person"? Could you upload the resulting image here so that I can check? At the weekend, I'll try to download your model and test it on my machine, but keep testing until there that you may find the bug.

**Comment by AlvaroCavalcante** [comment]
I'll close this issue due to inactivity, please, let me know if I could help you with something!

**Comment by andhana** [comment]
> @andhana the version that I used in my tests was the TF 1.14, but I'm not sure if this is a problem. Now that you fixed the "N/A" class, something different is being printed in the "class_name" or your unique result is still "person"? Could you upload the resulting image here so that I can check? At the weekend, I'll try to download your model and test it on my machine, but keep testing until there that you may find the bug.

Sorry for my slow response, this is the result of image and xml.
![image_2](https://user-images.githubusercontent.com/8891422/106007960-70243680-60e9-11eb-81df-b4b7d48ecb91.jpg)
![Screenshot from 2021-01-27 21-49-04](https://user-images.githubusercontent.com/8891422/106008070-88945100-60e9-11eb-8754-ab900e051238.png)
Screenshot of the xml.
![Screenshot from 2021-01-27 21-45-55](https://user-images.githubusercontent.com/8891422/106008138-977b0380-60e9-11eb-9dd8-16d572c585ed.png)

**Comment by AlvaroCavalcante** [comment]
@andhana this is strange, in your image you are correctly getting the class names, so in the XML you should get it too. When you open your original image and the generated XML in the annotation software (LabelImage for example) it shows the class "person" and "N/A" in the kite? I'll try to use your model to simulate this issue!

**Comment by andhana** [comment]
I have test it on 3 different computers (all ubuntu OS), the result still appears only one class name.
This is a screenshot of the printed class_name from the terminal
![Screenshot from 2021-02-03 16-54-57](https://user-images.githubusercontent.com/8891422/106730047-b9700b00-6640-11eb-8535-4ca9a03f1158.png)

**Comment by AlvaroCavalcante** [comment]
@andhana you tried to update your TensorFlow version to 1.4 or above in one of the machines? This is the version that I used. I'll download an example model and try to reproduce your error today ok? I'll give you feedback on my findings. Tanks!

**Comment by AlvaroCavalcante** [comment]
@andhana sorry for the late response, I was really busy. After analyse your issue I got some errors in the auto_annotate. I fixed and seems that It's all working now. I've tested using an SSD model from TF and it correctly gave me the results and annotate the files. Try again please and let me know if you have any issues!
